### PR TITLE
Use `files` property in package.json

### PR DESCRIPTION
**Pull request by kevva**

### CODE REVIEW

**Comment by feross** [comment]
what does this do?

**Comment by kevva** [comment]
Only includes files (plus `readme.md` automatically) in the `files`prop when publishing to npm.

**Comment by kevva** [comment]
ping @substack

**Comment by marco-c** [comment]
@substack would it be possible to merge this? We're trying to reduce the installation size of our `web-push` library (https://github.com/web-push-libs/web-push).

**Comment by substack** [comment]
I prefer when packages contain docs, tests, licensing, and examples.

**Comment by exogen** [comment]
> Bundling these artifacts makes it easier to verify things about the code later without hunting down the originating git repo which may not even exist anymore in a long enough time horizon.

But realistically, only a handful of people will do this, ever. 99.999999% of the installs that occur will simply be wasting space, and the vast majority of users aren't even aware that your modules exist or care about them, they just happen to appear in the dependency tree somewhere.

It is literally a joke people make about Node and npm that the `node_modules` tree is ridiculously large and unwieldy. Anything we can do to help with that matters. You may not care, but I just summed the size of *just* the `test` folders that appear in npm modules on my system, and the total is 2964 MB. Three gigabytes just for tests that will never be run, let alone looked at! The substack-owned modules "only" accounted for 240 MB, but still – given the current state of insane dependency trees, I feel this is perpetuating a bad practice.

**Comment by egoist** [comment]
Posterity will not thank us for taking down the original git repo.

**Comment by marco-c** [comment]
I feel like the original git repo is more likely to survive than the npm package and that saving space and bandwidth is very useful in some cases, but clearly this is your call.

**Comment by kgryte** [comment]
If you don't want tests included during install, nothing is stopping you from forking, updating, and publishing as a new package. Feel free to maintain your own version as you see fit.

**Comment by marco-c** [comment]
> If you don't want tests included during install, nothing is stopping you from forking, updating, and publishing as a new package. Feel free to maintain your own version as you see fit.

Yes, I'm aware of my freedom to create forks 😄 
I don't feel like it's important enough though, so I won't. Plus, I'm not sure how it works when you want to override a dependency of a dependency, and I don't really want to make my life more complicated over a bunch of kilobytes.

**Pull request closed without merging**
